# Generated by Django 3.2.8 on 2022-02-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Lavash', 'Lavash'), ('Chizburger', 'Chizburger'), ('Pizza', 'Pizza'), ('Shaverma', 'Shaverma'), ('Hotdog', 'Hotdog')], max_length=15)),
                ('sum', models.PositiveIntegerField(verbose_name='Narxi')),
                ('description', models.TextField(default='', max_length=225, null=True, verbose_name='Izoh')),
                ('Size', models.CharField(choices=[('Katta', 'Big'), ("O'rtacha", 'Middle'), ('Kichik', 'Little')], max_length=15)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
