# Generated by Django 3.2.8 on 2022-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220215_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='Size',
            field=models.CharField(choices=[('Katta', 'Big'), ("O'rtacha", 'Middle'), ('Kichik', 'Little')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='foods',
            name='type',
            field=models.CharField(choices=[('Lavash', 'Lavash'), ('Chizburger', 'Chizburger'), ('Pizza', 'Pizza'), ('Shaverma', 'Shaverma'), ('Hotdog', 'Hotdog'), ('Ichimliklar', 'Ichimliklar')], max_length=15),
        ),
    ]
