# Generated by Django 3.2.8 on 2022-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220216_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='full_name',
            field=models.CharField(auto_created=True, max_length=255),
        ),
    ]
