# Generated by Django 3.2.8 on 2022-02-18 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20220217_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='botuser',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
