# Generated by Django 3.2.8 on 2022-02-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220219_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='description_ru',
            field=models.TextField(default='', max_length=225, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='foods',
            name='title_ru',
            field=models.CharField(default='Ruscha', max_length=255, null=True),
        ),
    ]
