# Generated by Django 3.2.8 on 2022-03-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_foods_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='file',
        ),
    ]
